//
// Created by Lukas Brand on 30.06.2023.
//

#ifndef CSPOT_APPS_DF_LOGGER_SETTINGS_H
#define CSPOT_APPS_DF_LOGGER_SETTINGS_H

#define LOGGER_ENABLED
#define DIRECT_FLUSH

#include "df_logger.h"
enum LOG_LEVELS CURRENT_LOG_LEVEL = DF_TRACE;

#endif // CSPOT_APPS_DF_LOGGER_SETTINGS_H
